[package]
name = "camel_cards"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part_one"
path = "src/part_one/main.rs"

[[bin]]
name = "part_two"
path = "src/part_two/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
